name: Helm Publish
on:
  push:
    branches: [ 'main' ]
jobs:
  setup:
    name: Setup Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.16.0
  package:
    name: Package Helm Charts
    runs-on: ubuntu-latest
    needs: setup  # Waits for 'setup' job to complete
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Package Helm Charts
        shell: bash
        run: |
          mkdir -p dist  # Ensure dist directory exists
          find charts/ -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||' | sort | uniq | xargs --verbose -L 1 helm dep up
          for subdir in charts/*/; do
              echo "$subdir"
              helm package "$subdir" -u -d dist
          done
      - name: Archive dist directory
        uses: actions/upload-artifact@v3
        with:
          name: packaged-charts
          path: dist
  push:
    name: Push Helm Charts to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: package  # Waits for both 'package' job to complete
    steps:
      - name: Login to GitHub Container Registry
        shell: bash
        run: echo "${GITHUB_TOKEN}" | helm registry login ${REGISTRY} --username "${GITHUB_ACTOR}" --password-stdin
        env:
          REGISTRY: "ghcr.io/${{ github.repository }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Download packaged charts
        uses: actions/download-artifact@v3
        with:
          name: packaged-charts
          path: dist
      - name: Push packages
        shell: bash
        working-directory: dist
        run: |
          for f in *.tgz ; do
              echo "$f"
              helm push "$f" "oci://${REGISTRY}"
          done
        env:
          REGISTRY: "ghcr.io/${{ github.repository }}"
